#! /bin/bash

function on(){
	defaults write com.apple.dock tilesize -float 32;
	defaults delete com.apple.dock autohide-delay;
	killall Dock;
}

function off(){
	defaults write com.apple.dock tilesize -float 1;
	defaults write com.apple.dock autohide-delay -float 1000;
	killall Dock;
}

function toggle(){
	val=$(defaults read com.apple.dock tilesize);
	if [ $val -eq 32 ]; then
		echo "Turning off";
		off;
	else
		echo "Turning on";
		on;
	fi
}

toggle;
