#! /bin/bash

col(){
  case "$1" in
    red)     echo -e "\033[31m$2\033[0m" ;;
    green)   echo -e "\033[32m$2\033[0m" ;;
    yellow)  echo -e "\033[33m$2\033[0m" ;;
    blue)    echo -e "\033[34m$2\033[0m" ;;
    *)       echo -e "$2" ;;
  esac
}

# Download via ytdlp: opts=(a, nc)
function dl(){
  if [ "$2" = "a" ]; then
    echo $(col yellow "in Audio mode")
    cmd="yt-dlp \"$1\" -x --audio-format mp3 --audio-quality 0";
  else
    cmd="yt-dlp \"$1\"";
    if [[ "$1" == *"youtube.com"* ]]; then
      echo $(col yellow "in YouTube mode");
      cmd="$cmd -f \"[height<=720][ext=mp4]\"";
    else
      echo $(col yellow "in Generic mode");
    fi
  fi

  name="$(eval "$cmd --get-filename")";
  eval "$cmd";

  name2=$(clean "$name");
  mv "$name" "$name2";
  echo "$name2 Downloaded";
}

# Compress Video
function compress(){
  name="$1";
  rand=$(( ( RANDOM % 1000 )  + 1 ));

  # ask for bitrate
  if [ -z "$2" ]; then
    echo $(col yellow "Enter bitrate as <n>k (default 3000k):");
    read bitrate;
    if [ -z "$bitrate" ]; then
      bitrate="3000k";
    fi
  else
    bitrate="$2";
  fi

  echo $(col blue "Compressing $name");
  name2=$(clean "$name");

  ffmpeg -hide_banner -i "$name" -c:v h264_videotoolbox -b:v $bitrate -max_muxing_queue_size 1024 -threads:v 0 -y out_$rand.mp4;
  echo $(col yellow "Generated out_$rand.mp4");

  rm -rf "$name";
  mv out_$rand.mp4 "$name2";
  echo $(col yellow "Compressed to $name2")
}

"$@"
