#!/bin/bash

isWorking=0
ping -c 1 -W 100 google.com > /dev/null 2>&1 && isWorking=1 || isWorking=0
if [ $isWorking -eq 1 ]; then
  echo "ok."
  exit 0
fi


echo "   Restarting..."

DEV="en0"
networksetup -setairportpower "$DEV" off
sleep 0.5
networksetup -setairportpower "$DEV" on