#! /bin/bash

BASE="$HOME/Documents/bin";
OSADIR="$BASE/apple";

col(){
  case "$1" in
    red)     echo -e "\033[31m$2\033[0m" ;;
    green)   echo -e "\033[32m$2\033[0m" ;;
    yellow)  echo -e "\033[33m$2\033[0m" ;;
    blue)    echo -e "\033[34m$2\033[0m" ;;
    *)       echo -e "$2" ;;
  esac
}

function token(){
  . "$BASE/local/tokens.env";
  echo "${!1}";
}

function port(){
  if [ -z "$1" ]; then
    # list all open ports
    ports=$(lsof -i tcp -s tcp:listen | grep "IPv4" | awk '{print $9}' | tail -n +3)
    echo "$ports"
    # read port
    read -p "Port to kill: " port
    # if port is not in list, exit
    if ! echo "$ports" | grep -q "$port"; then
      echo "Port $port is not in list."
      exit 0
    fi
  else
    port=$1
  fi
  pid=$(lsof -i tcp:$port | awk '{print $2}' | tail -n1)

  kill -9 $pid
  echo "Port $1 is killed."
}

function commit() {
  git rev-parse --is-inside-work-tree &>/dev/null || {
    echo "Error: not a git repository"
    return 1
  }

  git add .

  if [ $# -eq 0 ]; then
    echo "Enter a commit message:"
    read -r msg
  else
    msg="$1"
  fi

  [ -z "$msg" ] && { echo "Error: no commit message"; return 1; }

  if [[ "$2" == "--days" ]]; then
    git commit --date "$3 day ago" -m "$msg"
  else
    git commit -m "$msg"
  fi

  branch="$(git branch --show-current)"

  if git rev-parse --abbrev-ref --symbolic-full-name @{u} &>/dev/null; then
    git pull
  fi

  if [[ "$2" == "-f" ]]; then
    if git rev-parse --abbrev-ref --symbolic-full-name @{u} &>/dev/null; then
      git push
    else
      git push --set-upstream origin main
    fi
  fi
}

function gcp(){
  git clone https://github.com/plutoniumm/$1 --depth 1;
}

function osa(){
  osascript "$OSADIR/$1.applescript";
}

function diff(){
  BASE="$(pwd)";

  dirs=$(find . -type d -name ".git" | grep -vE "node_modules" | sed 's/\.git//'| sed 's/.\///');
  for dir in $dirs; do
    cd "$BASE/$dir/"
    if [[ ! -d ".git" ]]; then
        cd ..;
        continue;
    fi

    diffCt=$(git diff --stat);
    if [ -n "$diffCt" ]; then
      ago=$(git log -1 --format=%ar);
      echo "$(col blue "$dir"): $(col yellow "$ago")";
      git diff --stat | cat;
    fi

    cd ..;
  done
}

"$@"
